# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 621eb934b60586a478a301fca61c598dfc0b3a5b05f6f90318927a871fd1dfc2b1ef41eaa143ab4b4ef052132f1e148e7a870b66ba8908b67228d3d050e86605

test:
  secret_key_base: 575e664eebce5a925fb5eef92626c8659dd38e45e634f37251b83a12071e7315baffd666e63e80b70ea80cb7c2e047cbe29fa400885d0a0c3f3b0b44cd9deed9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
